const menuItems: MenuItem[] = [
    {
        id: 1,
        commerceId: 1,
        name: 'Promo Especial 1',
        description: 'Deliciosa promoción 1 con los mejores ingredientes.',
        price: 4500,
        stock: true,
        image: [{ id: 1, name: 'promo1', type: 'image/png', url: require('../../assets/menu/Carrusel de promos -01.png') }],
        category: { id: 6, name: 'Combos', urlImage: null },
        dietaryRestrictions: [],
    },
    {
        id: 2,
        commerceId: 1,
        name: 'Promo Especial 2',
        description: 'Deliciosa promoción 2 con los mejores ingredientes.',
        price: 4600,
        stock: true,
        image: [{ id: 2, name: 'promo2', type: 'image/png', url: require('../../assets/menu/Carrusel de promos -02.png') }],
        category: { id: 1, name: 'Hamburguesas', urlImage: null },
        dietaryRestrictions: [],
    },
    {
        id: 3,
        commerceId: 1,
        name: 'Promo Especial 3',
        description: 'Deliciosa promoción 3 con los mejores ingredientes.',
        price: 4700,
        stock: true,
        image: [{ id: 3, name: 'promo3', type: 'image/png', url: require('../../assets/menu/Carrusel de promos -03.png') }],
        category: { id: 3, name: 'Pollos', urlImage: null },
        dietaryRestrictions: [],
    },
    {
        id: 4,
        commerceId: 1,
        name: 'Promo Especial 4',
        description: 'Deliciosa promoción 4 con los mejores ingredientes.',
        price: 4800,
        stock: true,
        image: [{ id: 4, name: 'promo4', type: 'image/png', url: require('../../assets/menu/Carrusel de promos -04.png') }],
        category: { id: 2, name: 'Pizza', urlImage: null },
        dietaryRestrictions: [],
    },
    {
        id: 5,
        commerceId: 1,
        name: 'Promo Especial 5',
        description: 'Deliciosa promoción 5 con los mejores ingredientes.',
        price: 4900,
        stock: true,
        image: [{ id: 5, name: 'promo5', type: 'image/png', url: require('../../assets/menu/Carrusel de promos -05.png') }],
        category: { id: 5, name: 'Alitas', urlImage: null },
        dietaryRestrictions: [],
    },
    {
        id: 6,
        commerceId: 1,
        name: 'Promo Especial 6',
        description: 'Deliciosa promoción 6 con los mejores ingredientes.',
        price: 5000,
        stock: true,
        image: [{ id: 6, name: 'promo6', type: 'image/png', url: require('../../assets/menu/Carrusel de promos -06.png') }],
        category: { id: 6, name: 'Combos', urlImage: null },
        dietaryRestrictions: [],
    },
    {
        id: 7,
        commerceId: 1,
        name: 'Promo Especial 7',
        description: 'Deliciosa promoción 7 con los mejores ingredientes.',
        price: 5100,
        stock: true,
        image: [{ id: 7, name: 'promo7', type: 'image/png', url: require('../../assets/menu/Carrusel de promos -07.png') }],
        category: { id: 1, name: 'Hamburguesas', urlImage: null },
        dietaryRestrictions: [],
    },
    {
        id: 8,
        commerceId: 1,
        name: 'Promo Especial 8',
        description: 'Deliciosa promoción 8 con los mejores ingredientes.',
        price: 5200,
        stock: true,
        image: [{ id: 8, name: 'promo8', type: 'image/png', url: require('../../assets/menu/Carrusel de promos -08.png') }],
        category: { id: 3, name: 'Pollos', urlImage: null },
        dietaryRestrictions: [],
    },
    {
        id: 9,
        commerceId: 1,
        name: 'Promo Especial 9',
        description: 'Deliciosa promoción 9 con los mejores ingredientes.',
        price: 5300,
        stock: true,
        image: [{ id: 9, name: 'promo9', type: 'image/png', url: require('../../assets/menu/Carrusel de promos -09.png') }],
        category: { id: 2, name: 'Pizza', urlImage: null },
        dietaryRestrictions: [],
    },
    {
        id: 10,
        commerceId: 1,
        name: 'Promo Especial 10',
        description: 'Deliciosa promoción 10 con los mejores ingredientes.',
        price: 5400,
        stock: true,
        image: [{ id: 10, name: 'promo10', type: 'image/png', url: require('../../assets/menu/Carrusel de promos -10.png') }],
        category: { id: 5, name: 'Alitas', urlImage: null },
        dietaryRestrictions: [],
    },
    {
        id: 11,
        commerceId: 1,
        name: 'Promo Especial 11',
        description: 'Deliciosa promoción 11 con los mejores ingredientes.',
        price: 5500,
        stock: true,
        image: [{ id: 11, name: 'promo11', type: 'image/png', url: require('../../assets/menu/Carrusel de promos -11.png') }],
        category: { id: 6, name: 'Combos', urlImage: null },
        dietaryRestrictions: [],
    },
    {
        id: 12,
        commerceId: 1,
        name: 'Promo Especial 12',
        description: 'Deliciosa promoción 12 con los mejores ingredientes.',
        price: 5600,
        stock: true,
        image: [{ id: 12, name: 'promo12', type: 'image/png', url: require('../../assets/menu/Carrusel de promos -12.png') }],
        category: { id: 1, name: 'Hamburguesas', urlImage: null },
        dietaryRestrictions: [],
    },
    {
        id: 13,
        commerceId: 1,
        name: 'Promo Especial 13',
        description: 'Deliciosa promoción 13 con los mejores ingredientes.',
        price: 5700,
        stock: true,
        image: [{ id: 13, name: 'promo13', type: 'image/png', url: require('../../assets/menu/Carrusel de promos -13.png') }],
        category: { id: 3, name: 'Pollos', urlImage: null },
        dietaryRestrictions: [],
    },
    {
        id: 14,
        commerceId: 1,
        name: 'Promo Especial 14',
        description: 'Deliciosa promoción 14 con los mejores ingredientes.',
        price: 5800,
        stock: true,
        image: [{ id: 14, name: 'promo14', type: 'image/png', url: require('../../assets/menu/Carrusel de promos -14.png') }],
        category: { id: 2, name: 'Pizza', urlImage: null },
        dietaryRestrictions: [],
    },
    {
        id: 15,
        commerceId: 1,
        name: 'Promo Especial 15',
        description: 'Deliciosa promoción 15 con los mejores ingredientes.',
        price: 5900,
        stock: true,
        image: [{ id: 15, name: 'promo15', type: 'image/png', url: require('../../assets/menu/Carrusel de promos -15.png') }],
        category: { id: 5, name: 'Alitas', urlImage: null },
        dietaryRestrictions: [],
    },
    {
        id: 16,
        commerceId: 1,
        name: 'Promo Especial 16',
        description: 'Deliciosa promoción 16 con los mejores ingredientes.',
        price: 6000,
        stock: true,
        image: [{ id: 16, name: 'promo16', type: 'image/png', url: require('../../assets/menu/Carrusel de promos -16.png') }],
        category: { id: 6, name: 'Combos', urlImage: null },
        dietaryRestrictions: [],
    },
    {
        id: 17,
        commerceId: 1,
        name: 'Promo Especial 17',
        description: 'Deliciosa promoción 17 con los mejores ingredientes.',
        price: 6100,
        stock: true,
        image: [{ id: 17, name: 'promo17', type: 'image/png', url: require('../../assets/menu/Carrusel de promos -17.png') }],
        category: { id: 1, name: 'Hamburguesas', urlImage: null },
        dietaryRestrictions: [],
    },
    {
        id: 18,
        commerceId: 1,
        name: 'Promo Especial 18',
        description: 'Deliciosa promoción 18 con los mejores ingredientes.',
        price: 6200,
        stock: true,
        image: [{ id: 18, name: 'promo18', type: 'image/png', url: require('../../assets/menu/Carrusel de promos -18.png') }],
        category: { id: 3, name: 'Pollos', urlImage: null },
        dietaryRestrictions: [],
    },
    {
        id: 19,
        commerceId: 1,
        name: 'Promo Especial 19',
        description: 'Deliciosa promoción 19 con los mejores ingredientes.',
        price: 6300,
        stock: true,
        image: [{ id: 19, name: 'promo19', type: 'image/png', url: require('../../assets/menu/Carrusel de promos -19.png') }],
        category: { id: 2, name: 'Pizza', urlImage: null },
        dietaryRestrictions: [],
    },
    {
        id: 20,
        commerceId: 1,
        name: 'Promo Especial 20',
        description: 'Deliciosa promoción 20 con los mejores ingredientes.',
        price: 6400,
        stock: true,
        image: [{ id: 20, name: 'promo20', type: 'image/png', url: require('../../assets/menu/Promos del fin de semana dores-01.png') }],
        category: { id: 5, name: 'Alitas', urlImage: null },
        dietaryRestrictions: [],
    },
];
